[package]
name = "ecc"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.13.1"
hmac = "0.12"
sha2 = "0.10"
ripemd = "0.1"
num-bigint = "0.4"
rand = "0.8"
hex = "0.4"

[lib]
doctest = false
